server:
  port: 0

spring:
  cloud:
    stream:
      function:
        bindings:
          messageInput-in-0: input
      bindings:
        input:
          destination: Message-exchange
          group: Message-queue
          consumer:
            max-attempts: 3
          binder: message-binder
      binders:
        message-binder:
          type: rabbit
          default-candidate: false
      rabbit:
        bindings:
          input:
            consumer:
              missing-queues-fatal: true
              queue-name-group-only: true
              declare-exchange: true
              bind-queue: true
              requeue-rejected: false
              transacted: true
              declareDlx: true
              autoBindDlq: true
